# Use official Python image from DockerHub
FROM python:3.9-slim

# Set a working directory inside the container
WORKDIR /app

# Copy the local app.py into the container
COPY python/app.py /app/

# Install Flask dependency
RUN pip install flask

# Expose port 5000 to access the app
EXPOSE 5000

# Command to run the Python app
CMD ["python", "app.py"]
